version: '2'

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx/letsencrypt:/etc/letsencrypt
      - ./nginx/keys:/etc/nginx/keys
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "443:443"
      - "80:80"
    networks:
      - outside
      - internal
  service:
    build:
      context: ./
    ports:
      - "3000:3000"
    networks:
      - internal
      - outside
    volumes:
      - ./logs/service:/opt/ethalarm/logs
  postgresql:
    image: 'docker/postgresql:latest'
    volumes:
      - postgresql_data:/var/lib/postgresql
    networks:
      - internal

volumes:
  postgresql_data: {}

networks:
  internal:
    internal: true
  outside:
    driver: bridge
